### ISSUE TITLE
Scan Status is Error

### ISSUE THREAD

**Issue by SSJune821** [Orange-Cyberdefense/grepmarx#7]
The scan showed an error in the status. May I know why? Or I want to know how to check the log. grepmarx is installed as docker.

![image](https://user-images.githubusercontent.com/26968714/230562114-e89801c5-03fe-4cf9-92b8-178e8f1837f0.png)

**Comment by R3zk0n** [comment]
You should be able to see the error message if you right-click on the Error button and inspect it, Typically from my experience it's due to a semgrep rule being broken

**Comment by griisemine** [comment]
If you have installed grepmarx on your Mac following the Docker procedure, you may encounter issues related to the absence of the "extract.json" file. In this case, it is recommended to create this file at the root of your project. 

Additionally, if you encounter other errors, you may resolve them by using only grepmarx rules that apply to your programming language.

To generate these rules, you can use the following command (replace "C" with your programming language):
```js
for (let i = 1; i < document.getElementById('rules-list-table').getElementsByTagName('tr').length; i++) {
  if (document.getElementById('rules-list-table').getElementsByTagName('tr')[i].getElementsByTagName('td')[4].innerText === 'C') {
    document.getElementById('rules-list-table').getElementsByTagName('tr')[i].getElementsByTagName('td')[0].getElementsByTagName('input')[0].click();
  }
}
```

I'm glad to hear that the previous actions helped solve your problems.

**Comment by fxbru** [comment]
Hey,

I confirm his is usually due to a "bad rule", or a rule that is not compatible with grepmarx's version of semgrep. Usually all rules from https://github.com/returntocorp/semgrep-rules are working fine.

Semgrep version will be updated in a further release.

To troubleshoot which rule is in fault, you can run semgrep CLI on the project, the rules you used for the scan are in `data/projects/<project_id>/rules`.

To answer the original question, as you used the docker install you can use this command to display all grepmarx logs:
`$ docker logs <grepmarx_container_id>`

If you leave your pointer on the "Error" red label, a bit more details should also appear on a tooltip.

**Comment by SSJune821** [comment]
I checked the log.

Error while scanning project with id=4: ('SemgrepError', "One of these properties is missing: 'languages'")
An error has occurred.

And the rules used https://github.com/returntocorp/semgrep-rules

I would appreciate it if you could let me know if the cause is speculated.

I'll keep looking for it, too.

Thank you.

**Comment by fxbru** [comment]
Semgrep has been bumped to version 1.59.1, this may resolve your issue. You might want to try out release v0.5.6.
